pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/soon2310020/php_ql_giaovien.git'
            }
        }
        stage('ABC'){

                def dockerHome = tool 'myDocker'
                env.PATH = "${dockerHome}/bin:${env.PATH}"
            steps{
                sh 'docker build -t sont457/docker-php.'
                sh 'docker push sont457/docker-php'
            }
        }
    }
}
