pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/soon2310020/php_ql_giaovien.git'
            }
        }
        stage('build_docker'){
            steps{
            withDockerRegistry(credentialsId: 'docker_login2', url: 'https://index.docker.io/v1/') {
                // some block
            }
            }
        }
    }
}
